In [7]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn import linear_model
import math

In [14]:
df = pd.read_csv('homeprices.csv')
df = df.head(5)
df

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       NaN   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000

In [16]:
median_bedrooms = math.floor(df['bedrooms'].median(skipna=True))
median_bedrooms

3

In [18]:
df['bedrooms'].fillna(median_bedrooms)

0    3.0
1    4.0
2    3.0
3    3.0
4    5.0
Name: bedrooms, dtype: float64

In [20]:
df['bedrooms'] = df['bedrooms'].fillna(median_bedrooms)
df

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       3.0   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000

In [23]:
reg = linear_model.LinearRegression()
reg.fit(df[['area', 'bedrooms', 'age']], df[['price']])

LinearRegression()

In [24]:
reg.coef_

array([[   137.25, -26025.  ,  -6825.  ]])

In [25]:
reg.intercept_

array([383725.])

In [27]:
reg.predict([[3000, 3, 40]])

C:\Users\user\anaconda3\lib\site-packages\sklearn\base.py:464: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([[444400.]])

In [28]:
reg.intercept_[0] + 3000 * reg.coef_[0][0] + 3 * reg.coef_[0][1] + 40 * reg.coef_[0][2]

444400.0000000001

In [29]:
reg.predict([[2500, 4, 5]])

C:\Users\user\anaconda3\lib\site-packages\sklearn\base.py:464: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([[588625.]])

### Homework:

In [30]:
! pip install word2number

  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
  Created wheel for word2number: filename=word2number-1.1-py3-none-any.whl size=5588 sha256=eec0b6d63a350d227cb2e2673e03a21ee715d19b1d572a52761f199481d0b8e8
  Stored in directory: c:\users\user\appdata\local\pip\cache\wheels\a0\4a\5b\d2f2df5c344ddbecb8bea759872c207ea91d93f57fb54e816e
Successfully built word2number


In [39]:
from word2number import w2n

In [55]:
df_hw = pd.read_csv('hiring.csv')
df_hw

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0        NaN                    8.0                           9      50000
1        NaN                    8.0                           6      45000
2       five                    6.0                           7      60000
3        two                   10.0                          10      65000
4      seven                    9.0                           6      70000
5      three                    7.0                          10      62000
6        ten                    NaN                           7      72000
7     eleven                    7.0                           8      80000

In [56]:
df_hw['experience'] = df_hw['experience'].fillna('zero')
df_hw

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0       zero                    8.0                           9      50000
1       zero                    8.0                           6      45000
2       five                    6.0                           7      60000
3        two                   10.0                          10      65000
4      seven                    9.0                           6      70000
5      three                    7.0                          10      62000
6        ten                    NaN                           7      72000
7     eleven                    7.0                           8      80000

In [57]:
# Convert each word in the 'experience' column to its corresponding integer
df_hw['experience'] = df_hw['experience'].apply(w2n.word_to_num)
df_hw

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0           0                    8.0                           9      50000
1           0                    8.0                           6      45000
2           5                    6.0                           7      60000
3           2                   10.0                          10      65000
4           7                    9.0                           6      70000
5           3                    7.0                          10      62000
6          10                    NaN                           7      72000
7          11                    7.0                           8      80000

In [59]:
median_test_score = df_hw['test_score(out of 10)'].median(skipna=True)
median_test_score

8.0

In [60]:
df_hw['test_score(out of 10)'] = df_hw['test_score(out of 10)'].fillna(median_test_score)
df_hw

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0           0                    8.0                           9      50000
1           0                    8.0                           6      45000
2           5                    6.0                           7      60000
3           2                   10.0                          10      65000
4           7                    9.0                           6      70000
5           3                    7.0                          10      62000
6          10                    8.0                           7      72000
7          11                    7.0                           8      80000

In [61]:
reg_hw = linear_model.LinearRegression()
reg_hw.fit(df_hw[['experience', 'test_score(out of 10)', 'interview_score(out of 10)']], df_hw[['salary($)']])

LinearRegression()

In [62]:
print(reg_hw.coef_)
print(reg.intercept_)

[[2812.95487627 1845.70596798 2205.24017467]]
[383725.]


In [63]:
reg_hw.predict([[2, 9, 6]])

C:\Users\user\anaconda3\lib\site-packages\sklearn\base.py:464: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([[53205.96797671]])

In [64]:
reg_hw.predict([[12, 10, 10]])

C:\Users\user\anaconda3\lib\site-packages\sklearn\base.py:464: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([[92002.18340611]])