In [1]:
import pandas as pd
import numpy as np
from sklearn import linear_model 

In [2]:
df = pd.DataFrame({
    'area': [2600, 3000, 3200, 3600, 4000], 
    'price': [550000, 565000, 610000, 680000, 725000]
})
print(df)

   area   price
0  2600  550000
1  3000  565000
2  3200  610000
3  3600  680000
4  4000  725000


In [3]:
reg = linear_model.LinearRegression()
X = df[['area']]
y = df[['price']]
reg.fit(X, y)

LinearRegression()

In [4]:
reg.predict([[3300]])

C:\Users\user\anaconda3\lib\site-packages\sklearn\base.py:464: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([[628715.75342466]])

In [5]:
reg.coef_

array([[135.78767123]])

In [6]:
reg.intercept_

array([180616.43835616])

### pickle:

In [7]:
import pickle

In [8]:
with open('model_pickle', 'wb') as f:
    pickle.dump(reg, f)

In [11]:
with open('model_pickle', 'rb') as f:
    mp = pickle.load(f)

In [13]:
mp.predict([[3300]])

C:\Users\user\anaconda3\lib\site-packages\sklearn\base.py:464: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([[628715.75342466]])

In [14]:
mp.coef_

array([[135.78767123]])

In [15]:
mp.intercept_

array([180616.43835616])

### joblib:

In [17]:
import joblib

In [18]:
joblib.dump(reg, 'model_joblib')

['model_joblib']

In [19]:
mj = joblib.load('model_joblib')

In [20]:
mj.predict([[3300]])

C:\Users\user\anaconda3\lib\site-packages\sklearn\base.py:464: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([[628715.75342466]])

In [21]:
mj.coef_

array([[135.78767123]])

In [22]:
mj.intercept_

array([180616.43835616])